### PR TITLE
To pass custom data in query parameter

### PR DESCRIPTION
**Pull request by olegabr**
There is a query option in flow.js object, and it sends it's contents to php in params member of the Request object. BUT! it is not accessible in client code. This PR makes it possible to access custom params specified in client part in the query option.

### CODE REVIEW

**Comment by lsm79** [comment]
Hello can you merge this PR with the master ?

**Comment by lsm79** [comment]
Hello @AidasK  thank you for the merge. it work great on my side, can you create a new release with this ?

**Comment by AidasK** [comment]
Sure, done

**Comment by lsm79** [comment]
Thanks !

**Pull request merged**
